version: '3.7'
services:
  app:
    build: app/
    volumes:
      - static:/usr/local/App42PaaS-Java-MySQL-Sample/target/

  tomcat:
    image: tomcat:9.0.0.M15-jre8-alpine
    ports:
      - "80:8080"
    volumes:
      - static:/usr/local/tomcat/webapps

  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"

volumes:
  static:
